# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: react-app
  labels:
    app: react-app
spec:
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
  selector:
    app: react-app
  type: ClusterIP