name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  # ------------- Build & Test ----------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run ESLint (code quality)
        run: npm run lint

      # (Optional) You don't have unit tests in package.json, so I skipped npm test
      # If you add vitest or jest later, you can enable:
      # - name: Run unit tests
      #   run: npm test

      - name: Build Vite app
        run: npm run build

  # ------------- Docker Build & Push to ECR ----------------
  push:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:${{ github.run_id }}

    # ------------- Update Helm Chart ----------------
  update-helm:
    runs-on: ubuntu-latest
    needs: push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
          fetch-depth: 0   # fetch full history so we can merge branches

      - name: Set up Git
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "GitHub Actions"

      - name: Sync deploy with main
        run: |
          git fetch origin
          # create deploy branch if it doesn’t exist, else switch to it
          git checkout deploy || git checkout -b deploy
          # merge latest main into deploy
          git merge origin/main --no-edit || true

      - name: Update Helm chart tag
        run: |
          sed -i "s|tag: .*|tag: \"${{ github.run_id }}\"|" helm/react-chart/values.yaml
          git add helm/react-chart/values.yaml
          git commit -m "Update image tag to ${{ github.run_id }}" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push origin deploy
